

#define ERR_CDS_CREATE_DATASTORE_00 "CDS INSUFFICIENT ARGUMENTS"
#define ERR_CDS_CREATE_DATASTORE_01 "SCHEMA FILE DOESNOT EXIST"
#define ERR_CDS_CREATE_DATASTORE_02 "DATASTORE NOT CREATED"

#define ERR_CDS_LOAD_DATASTORE_00 "LOAD-INSUFFICIENT ARGUMENTS"
#define	ERR_CDS_LOAD_DATASTORE_01 "CDS NOT LOADED" 

#define ERR_CDS_INSERT_DATASTORE_00 "INSERT INSUFFICIENT ARGUMENTS"
#define ERR_CDS_INSERT_DATASTORE_01 "NO.OF VALUES LESS THAN NO.OF COLUMNS"
#define ERR_CDS_INSERT_DATASTORE_02 "DUPLICATE RECORD - NOT INSERTED"

#define ERR_CDS_RETRIEVE_DATASTORE_00 "RETRIEVE INSUFFICIENT ARGUMENTS"
#define ERR_CDS_RETRIEVE_DATASTORE_01 "COLUMN NAME DOES NOT EXIST"
#define ERR_CDS_RETRIEVE_DATASTORE_02 "RECORD TO BE RETRIEVED NOT FOUND"

#define ERR_CDS_UPDATE_DATASTORE_00 "UPDATE INSUFFICIENT ARGUMENTS"
#define ERR_CDS_UPDATE_DATASTORE_01 "COLUMN NAME DOES NOT EXIST"
#define ERR_CDS_UPDATE_DATASTORE_02 "RECORD TO BE UPDATED NOT FOUND"
#define ERR_CDS_UPDATE_DATASTORE_03 "DUPLICATE KEY VALUE"

#define ERR_CDS_DELETE_DATASTORE_00 "DELETE INSUFFICIENT ARGUMENTS"
#define ERR_CDS_DELETE_DATASTORE_01 "RECORD TO BE DELETED DOES NOT EXIST"

#define ERR_CDS_UNLOAD_DATASTORE_00 "INSUFFICIENT ARGUMENTS"
#define ERR_CDS_UNLOAD_DATASTORE_01 "DATASTORE NOT CREATED/LOADED"






