#define SUCCESS_CDS_CREATE_DATASTORE_00 "DATASTORE CREATED SUCCESSFULLY"

#define SUCCESS_CDS_CREATE_DATASTORE_01 "DATASTORE LOADED SUCCESSFULLY"

#define SUCCESS_CDS_INSERT_DATASTORE_00 "DATA INSERTED SUCCESSFULLY"

#define SUCCESS_CDS_RETRIEVE_DATASTORE_00 "RETRIEVE SUCCESSFUL - "

#define SUCCESS_CDS_UPDATE_DATASTORE_00 "UPDATE SUCCESSFUL"

#define SUCCESS_CDS_DELETE_DATASTORE_00 "DELETE SUCCESSFUL"

#define SUCCESS_CDS_UNLOAD_DATASTORE_00 "UNLOAD SUCCESSFUL"

#define SUCCESS_CDS_LOAD_DATASTORE_00 "LOAD SUCCESSFUL"




